# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

services:
  ckan-dev:
    init: true
    volumes:
      # Mount the root directory from within development/external/ckan/contrib/docker
      - ../../../:/srv/app/src_extensions/ckanext-feedback
      - /srv/app/src_extensions/ckanext-feedback/development/